### ISSUE TITLE
Wrong Winning Token, needs an offset of 1 

### ISSUE THREAD

**Issue by SQasimHamdani** [SQasimHamdani/zerolotteryfrontend#3]
=winning number is 4062 on the backend.
but the lottery is showing 4063.
It's incrementing by 1 number.

it's for the weekly lottery.

**Comment by BluuJo** [comment]
I'm not getting the wrong number after many tests

**Comment by SQasimHamdani** [comment]
See on the website, it says token no 4063 won, but actually 4062 won.

Frontend
![image](https://user-images.githubusercontent.com/35899401/162644462-1fe5a8d5-3c48-4546-8fa9-96773845d4b7.png)

White actually in the backend
![image](https://user-images.githubusercontent.com/35899401/162644693-542dd995-3367-47a0-a4e2-4ccff8426b78.png)

**Comment by SQasimHamdani** [comment]
![image](https://user-images.githubusercontent.com/35899401/164536987-bf60ea59-2ed3-49e6-bf96-be1d15d37884.png)

fixed
